Add Fernsehturm and Windräder
placeDE/pixel pull request #209
Opened 2022-04-03 21:40 UTC by Xyaren

2022-04-03 21:40 UTC, Xyaren commented
https://discord.com/channels/297765871122907136/959922396272402502/960283694105509888

2022-04-04 09:39 UTC, jojo364 commented
Muss geändert werden

2022-04-04 09:43 UTC, mp14O4 requested changes
Fernsehturm muss aktualisiert werden

2022-04-04 10:33 UTC, closed without merging

2022-04-04 10:33 UTC, mp14O4 commented
In anderen Commits mittlerweile hinzugefügt